### ISSUE TITLE
这一套不适用yolov8m或者l模型，后处理的代码是有问题的

### ISSUE THREAD

**Issue by hacktmz** [cqu20160901/yolov8n_onnx_tensorRT_rknn_horizon#1]
如果只有一个类别，首先headNum应该是输出框框的个数吧，index=0的时候cls=output[1]就越界了
    for index in range(headNum):
        reg = output[index * 2 + 0]
        cls = output[index * 2 + 1]

**Comment by hacktmz** [comment]
代码是否可以考虑修改成兼容m和l 模型通用代码呢

**Comment by cqu20160901** [comment]
后处理是通用的兼容yolov8m和l

**Comment by hacktmz** [comment]
> 后处理是通用的兼容yolov8m和l

我这边尝试了yolov8m输出是1X84X8400，您的模型输出比这个会多好多个。加载模型推理后，后处理直接报错的

**Comment by cqu20160901** [comment]
本仓库示例给的后处理是为板端芯片部署导出的，规避了一些层目的是板端芯片上可以部署。1X84X8400是标准的模型输出，不适本仓库的示例后处理。本仓库适配的导出onnx的方法请参考 https://blog.csdn.net/zhangqian_1/article/details/128918268
